// @ts-nocheck 

import type { NextPage } from 'next'
import { useState, useEffect, useRef } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import styled from 'styled-components'
import variables from '../../styles/variables.module.scss'
import TextInput from '../../widgets/TextInput'
import Spacer from '../../widgets/Spacer'
import Button from '../../widgets/Button'


interface User {
    background: string;
    height: string;
    borderRadius: string;
}
const CenterWrapper = styled.div(
    ({ height, background, borderRadius }: User) => `
  background: ${background};
  justify-content: center;
  align-items: center;
  display: flex;
  height: ${height};
  flex-direction: column;
  border-radius:${borderRadius};
`
)


// const TomatoButton = styled(Button)`
//   background: tomato;
// `

const Register: NextPage = () => {

    const textInput = useRef<HTMLInputElement>(null);

    const register = () => {
        textInput?.current?.focus();
        console.log('haii')
    }


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-row">
                <div className="basis-1/2 min-h-screen relative">
                    <Image
                        // layout="responsive"
                        src="/ben-white-EMZxDosijJ4-unsplash.jpg"
                        alt="Picture of the author"
                        layout="fill"
                        objectFit="cover"
                        quality={100}
                    // placeholder="blur"
                    />
                </div>
                <div className="basis-1/2 p-20 bg-zinc-100">
                    <CenterWrapper height={"60%"} background="#fff" borderRadius={"10px"}>
                        <Spacer height={'20px'} />
                        <h2 className='text-center text-sm md:text-2xl lg:text-3xl '>Sign Up</h2>
                        <Spacer height={'20px'} />

                        <TextInput width='80%' placeholder='Name' />
                        <Spacer height={'10px'} />
                        <TextInput width={'80%'} ref={textInput} placeholder='Email' />
                        <Spacer height={'10px'} />

                        <TextInput width={'80%'} placeholder='Password' />
                        <Spacer height={'10px'} />

                        <TextInput width={'80%'} placeholder='Repeat Password' />

                        <Spacer height={'20px'} />
                        <Button width={'80%'} title="Register" onClick={() => { register() }} />
                        <Spacer height={'20px'} />
                    </CenterWrapper>
                    {/* <button className="outline outline-offset-2 outline-blue-500">Button A</button> */}
                </div>

            </div>

            {/* <div className="grid-cols-6" >
        <Image
          layout="fill"
          src="/surface-E9NcsvbRVqo-unsplash.jpg"
          alt="Picture of the author"
          width={500}
          height={500}
        />


        <main className={styles.main}>

        </main>


      </div> */}


            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </>
    )
}

export default Register
